apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: datasync-cronjob
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  jobTemplate:
    # metadata:
    #   annotations:
    #     alpha.image.policy.openshift.io/resolve-names: '*'
    spec:
      template:
        spec:
          containers:
          - env:
            - name: PGSQL_SERVER
              value: transientdb
            - name: PGSQL_PORT
              value: "5432"
            - name: AWS_ACCESS_KEY_ID
              value: AKIAVRYX3P5WG7ZKXZU2
            - name: AWS_SECRET_ACCESS_KEY
              value: pCMSBBivxwcCKAzE+TPwTwCT6TFNgan2voe8zwK 
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: IS_CRON
              value: "YES"
            image: dvzpoc/edgeonprem_eam_datasynchmodule:v15
            #command: ["ls"]
            #args: [""]
            imagePullPolicy: Always
            name: datasync
          restartPolicy: Never
  schedule: "0 11 * * *"
  #startingDeadlineSeconds: 600
  #successfulJobsHistoryLimit: 3
  suspend: false


          