apiVersion: v1
kind: Service
metadata:
  name: postgressqlui1-adminer-service
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 32765
  selector:
    rep-app: postgressqlui1-adminer1
