apiVersion: v1
kind: Service
metadata:
  name: postgressqlui2-pgadmin-service
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 32764
  selector:
    rep-app: postgressqlui2-pgadmin
