apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    rep-app: kafka
