apiVersion: v1
kind: Service
metadata:
  name: transientui-db-service
spec:
  type: NodePort
  ports:
  - name: "5555"
    port: 5555
    targetPort: 8080
    nodePort: 32762
  selector:
    app: transientui-db

